### PR TITLE
Modify the forms style.

### PR DESCRIPTION
**Pull request by yossef-khaled**
Screenshot 2022-01-31 at 23-40-44 Salam سلام
Done. But I changed how the user role and the image are positioned. cool ?

### CODE REVIEW

**Comment by MohamedAssaf** [comment]
Thank you for your comments on your pull requests. Very helpful. 

Can we add make the other forms display the images with the same style? Label above the image not side by side? 
Also have you checked this in mobile view?

**Comment by yossef-khaled** [comment]
Ok, I will make the same change for every form.
No, but I think as it is centered it will the same, but I will check them in mobile view.

**Comment by yossef-khaled** [comment]
**All the form are the same as the charity**
Volunteer-form
-------------------------------------------------
Disabled-form

**Comment by yossef-khaled** [comment]
**Forms mobile view**
Charity-Institution-form-mobile
Disabled-form-mobile
Volunteer-form-mobile

**Pull request merged**
